### ISSUE TITLE
After export framework, use framework crash

### ISSUE THREAD

**Issue by bearnewboy** [yourkarma/JWT#110]
My framework info : Architectures in the fat file: JWT.framework/JWT are: i386 x86_64 armv7 arm64

My project use framework crash : 
![screen shot 2016-11-25 at 3 49 05 pm](https://cloud.githubusercontent.com/assets/23735350/20617903/04b22e62-b327-11e6-98ad-e0cefcef9525.png)

**Comment by lolgear** [comment]
@bearnewboy hi! Could you share your code as 'code' (not image)?

I would like to use it as a test part.

**Comment by lolgear** [comment]
Could you share the version number of framework?

**Comment by bearnewboy** [comment]
Framework version : **2.2.0**

The **publicKey** and **message**  are from **JWT Tests** Project

My code :
```
#import "ViewController.h"
#import <JWT/JWT.h>

@interface ViewController ()

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    
    NSString *publicKey = @"MIICnTCCAYUCBEReYeAwDQYJKoZIhvcNAQEFBQAwEzERMA8GA1UEAxMIand0LTIwNDgwHhcNMTQwMTI0MTMwOTE2WhcNMzQwMjIzMjAwMDAwWjATMREwDwYDVQQDEwhqd3QtMjA0ODCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKhWb9KXmv45+TKOKhFJkrboZbpbKPJ9Yp12xKLXf8060KfStEStIX+7dCuAYylYWoqiGpuLVVUL5JmHgXmK9TJpzv9Dfe3TAc/+35r8r9IYB2gXUOZkebty05R6PLY0RO/hs2ZhrOozHMo+x216Gwz0CWaajcuiY5Yg1V8VvJ1iQ3rcRgZapk49RNX69kQrGS63gzj0gyHnRtbqc/Ua2kobCA83nnznCom3AGinnlSN65AFPP5jmri0l79+4ZZNIerErSW96mUF8jlJFZI1yJIbzbv73tL+y4i0+BvzsWBs6TkHAp4pinaI8zT+hrVQ2jD4fkJEiRN9lAqLPUd8CNkCAwEAATANBgkqhkiG9w0BAQUFAAOCAQEAnqBw3UHOSSHtU7yMi1+HE+9119tMh7X/fCpcpOnjYmhW8uy9SiPBZBl1z6vQYkMPcURnDMGHdA31kPKICZ6GLWGkBLY3BfIQi064e8vWHW7zX6+2Wi1zFWdJlmgQzBhbr8pYh9xjZe6FjPwbSEuS0uE8dWSWHJLdWsA4xNX9k3pr601R2vPVFCDKs3K1a8P/Xi59kYmKMjaX6vYT879ygWt43yhtGTF48y85+eqLdFRFANTbBFSzdRlPQUYa5d9PZGxeBTcg7UBkK/G+d6D5sd78T2ymwlLYrNi+cSDYD6S4hwZaLeEK6h7p/OoG02RBNuT4VqFRu5DJ6Po+C6JhqQ=="; // load public key. Or use it as raw string.
    
    NSString *algorithmName = @"RS256";
    NSString *message = @"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJoZWxsbyI6ICJ3b3JsZCJ9.AzXfyb6BuwLgNUqVkfiKeQRctG25u3-5DJIsGyDnFxOGTet74SjW6Aabm3LSXZ2HgQ5yp8_tCfqA12oDmPiviq4muhgc0LKujTpGtFlf0fcSJQJpxSTMGQZdZnxdKpz7dCSlQNvW6j1tGy1UWkXod-kf4FZckoDkGEbnRAVVVL7xRupFtLneUJGoWZCiMz5oYAoYMUY1bVil1S6lIwUJLtgsvrQMoVIcjlivjZ8fzF3tjQdInxCjYeOKD3WQ2-n3APg-1GEJT-l_2y-scbE55TPSxo9fpHoDn7G0Kcgl8wpjY4j3KR9dEa4unJN3necd83yCMOUzs6vmFncEMTrRZw";
    
    JWTBuilder *decodeBuilder = [JWTBuilder decodeMessage:message].secret(publicKey).algorithmName(algorithmName).algorithm([JWTAlgorithmRSBase algorithm256]);
    NSDictionary *envelopedPayload = decodeBuilder.decode;
    
    // check error
    if (decodeBuilder.jwtError) {
        // error occurred.
    }
    
    NSLog(@"🎾🎾🎾 %@",envelopedPayload);
}

@end
```

**Comment by lolgear** [comment]
@bearnewboy how did you install framework?

**Comment by lolgear** [comment]
@bearnewboy could you share your test project? It seems that your install process causes this error

**Comment by bearnewboy** [comment]
I use your **/Framework/JWT.xcodeproj**, then use Xcode build. The production JWT.framework drag and copy into my test project.

my  test project below : 
[TestJWT.zip](https://github.com/yourkarma/JWT/files/615182/TestJWT.zip)

**Comment by lolgear** [comment]
@bearnewboy oh, interesting. 
Not a mainstream with dependency managers :)
Somehow, `[decodeBuilder decodeMessage:]` not create new builder and return `nil` instead.

**Comment by lolgear** [comment]
@bearnewboy thank you!
Two bugs in code and one in dependencies.

First, you should add all local frameworks as 'Embedded frameworks' ( they are shipped with your binary and copied. )

1. Choose project.
2. Choose General tab.
3. Remove all occurrences of JWT framework in section (Link with binary).
4. Add JWT framework as Embedded ( section Embedded frameworks ).

And two bugs:

1. `algorithm` is broken, it doesn't set specified algorithm, so, use `algorithmName(JWTAlgorithmNameRS256)` instead.
2. `secret` did not decoded well, searching solution for this bug.

**Comment by bearnewboy** [comment]
@lolgear thank you very much!
It works well for me.
