### ISSUE TITLE
"jwtSecret" and "secret" both deprecated. 

### ISSUE THREAD

**Issue by jonny999** [yourkarma/JWT#111]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/yourkarma/JWT/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/yourkarma/JWT#documentation)
* [x] I have searched for a similar issue in the [project](https://github.com/yourkarma/JWT/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios 
 Platform Version        | e.g. 8.0
 Version                       | e.g. 2.2.0
 Integration Method      | e.g. manually
 Xcode Version           | e.g. Xcode 8.0
 Repro rate              | e.g. all the time (100%)
 Demo project link       | e.g. none

### Issue Description and Steps

"jwtSecret" and "secret" is deprecated. I guess the "jwtSecret" shouldn't be deprecated because it is used in method "decodeHelper". Documentation is only for 2.0.

**Comment by lolgear** [comment]
@jonny999 hi! you correct. New API draft will be here soon!

**Comment by jonny999** [comment]
Thanks for quick answer.

**Comment by lolgear** [comment]
@jonny999, please, have a look at new version!

**Comment by lolgear** [comment]
https://github.com/yourkarma/JWT/releases/tag/3.0.0-beta.1

**Comment by lolgear** [comment]
could be closed?

**Comment by jonny999** [comment]
hi, thanks. Yes, you can close it.
