### ISSUE TITLE
Error with JWTBuilder, Undefined symbols

### ISSUE THREAD

**Issue by marcocasadio** [yourkarma/JWT#125]
Hi,
I'm using last beta in my Xcode project and I downloaded the JWT package by Cocoapods.
I've included, in header of my controller, this:
`#import <JWT/JWT.h>`

I'm just trying to decode e JWT token string, with this simple line:
`JWTBuilder *builder = [JWTBuilder decodeMessage:token].algorithmName(algorithmName).options(@(YES));
`
but I get an error when I run it (see the attachment).

Anyone can help me? I've already deleted all DerivedData/*

Thanks

<img width="997" alt="schermata 2017-03-01 alle 02 28 06" src="https://cloud.githubusercontent.com/assets/7057518/23442199/6c4b85aa-fe27-11e6-9907-6fb8a3b8d586.png">

**Comment by lolgear** [comment]
Try new version 3.0 as a hotfix:

```
id<JWTAlgorithmAndDataHolder> holder = [JWTAlgorithmHSFamilyDataHolder new].algorithmName(algorithmName)
JWTCodingBuilder *builder = [JWTDecodingBuilder decodeMessage:token].addHolder(holder).options(JWTCodingDecodingOptionsSkipVerification);
builder.result;
```

**Comment by lolgear** [comment]
@marcocasadio could you show podfile and also share sample project?

**Comment by marcocasadio** [comment]
Hi, I've resolved!
There was some warning (not error!) so I removed some settings from Build Phases.
Now it works!

**Comment by lolgear** [comment]
Happy to hear from you! :) close when you are ready!

**Comment by lolgear** [comment]
@marcocasadio closed?
