### ISSUE TITLE
Import without using cocoapod or carthage

### ISSUE THREAD

**Issue by Azuritul** [yourkarma/JWT#129]
This is not an issue but a question.  Is there anyway I can import this library to my project without using Cocoapod or Carthage?  I copied the source code but it tells me that `<JWT/JWT.h>` cannot be found.   Any hint is appreciated.

Cheers

**Comment by lolgear** [comment]
@Azuritul I suppose that another issue #127 could be connected.

However, try to use plain import `#import "JWT.h" `

**Comment by Azuritul** [comment]
I think I'll use `#import "JWT.h"` for now. Thank you for the suggestion.
