### ISSUE TITLE
JWTClaimsSet not showing value in payload

### ISSUE THREAD

**Issue by kashiftriffort** [yourkarma/JWT#131]
I need to pass issuedAt and expirationDate using JWTClaimsSet. When I try to encode payload values after encodeClaimsSet, token generated showing wrong values. I am not getting payload values from token generated in payload section, it showing in header section. Please let me know what I am doing wrong.

    JWTClaimsSet *claimsSet = [[JWTClaimsSet alloc] init];
    NSDate *currentDate = [NSDate date];
    claimsSet.issuedAt = currentDate;
    claimsSet.expirationDate = [currentDate dateByAddingTimeInterval:15];
    
    NSString *secret = @"secret";
    id<JWTAlgorithm> algorithm = [JWTAlgorithmFactory algorithmByName:@"HS256"];
    JWTBuilder *encodeBuilder = [JWT encodeClaimsSet:claimsSet];
    NSString *testResult = encodeBuilder.secret(secret).algorithm(algorithm).headers(payload).encode;

**Comment by lolgear** [comment]
Hi!
You put payload in headers section.
```
NSString *testResult = encodeBuilder.secret(secret).algorithm(algorithm).headers(payload).encode;
```
I am not sure, that claims and payloads are supported simultaneously now. ( And I am not sure if it possible in standard )

You could encode either payload or claims. ( in current implementation ).

**Comment by kashiftriffort** [comment]
I have seen that is possible in Android repo, one of my devs have done
claimsSet and Payload in one .

**Comment by kashiftriffort** [comment]
Claims and Payload both are working simultaneously in Android. Token generated showing payload and claims both in payload section. How that is done in Android.

**Comment by lolgear** [comment]
Could you add reference to appropriate standard documentation?

Maybe I miss something.

**Comment by kashiftriffort** [comment]
I am not able to download latest version of JWT via podfile. I am using this pod "JWT-3.0.0-beta.2". Please let me know if this is correct or any other thing is required

**Comment by kashiftriffort** [comment]
This is the android code. Please let me know if this is possible in iOS. As I have tried many ways of doing.

Jwts.builder().claim("email",username).claim("password",password).claim("type","WIFOG").claim("app","1").claim("login","app")
                    .setIssuedAt(new Utility(mContext).getNowTime().getTime()).setExpiration( new Utility(mContext).getExpTime().getTime())
                    .signWith(SignatureAlgorithm.HS256, Defines.SECRET_KEY.getBytes())
                    .compact();

**Comment by lolgear** [comment]
@kashiftriffort These 'claims' are not standard claims.
Non-standard 'claims' are not supported right now.

```
pod 'JWT', '3.0.0-beta.3'
```

Could you provide a token for your example with SecretKey in Base64 format ( or without signing by applying None algorithm )?

**Comment by kashiftriffort** [comment]
Token:

eyJsb2dpbiI6ImFwcCIsInBhc3N3b3JkIjoiMTIzNDU2NzgiLCJhcHAiOiIxIiwiYWxnIjoiSFMyNTYiLCJlbWFpbCI6Imthc2hpZmppbGFuaTE5OTFAZ21haWwuY29tIiwidHlwZSI6IldJRk9HIiwidHlwIjoiSldUIn0.eyJleHAiOjE0OTY5ODEzOTUsImlhdCI6MTQ5Njk4MTM4MH0.dfRPwlUh4Jo9sNvaQY4-nuqqIKZSoNp7Qo4caQAqUzM

SecretKey in Base64 format

c2VjcmV0

Below are the information coming in Header section, however I want that in Payload section.

  "login": "app",
  "password": "12345678",
  "app": "1",
  "email": "kashifjilani1991@gmail.com",
  "type": "WIFOG",

**Comment by alexshepard** [comment]
Hi, for what it's worth, mixing reserved (what this library calls a ClaimsSet) and public/private (what this library calls a payload) claims seems to be supported in the JWT RFC, and is even listed as an example in the RFC doc. 

From https://tools.ietf.org/html/rfc7519:
```
     {"iss":"joe",
      "exp":1300819380,
      "http://example.com/is_root":true}
```

**Comment by lolgear** [comment]
@alexshepard @kashiftriffort 

Could you check latest master?

#134

**Comment by lolgear** [comment]
@alexshepard @kashiftriffort 
could it be closed?
