### ISSUE TITLE
Error when using KeyExtractor: Use of unresolved identifier 'JWTCryptoKeyExtractor'

### ISSUE THREAD

**Issue by andriajensen** [yourkarma/JWT#136]
### New Issue Checklist

* [x ] I have read and understood the [CONTRIBUTING guide](https://github.com/yourkarma/JWT/blob/master/.github/CONTRIBUTING.md)
* [ x] I have read the [Documentation](https://github.com/yourkarma/JWT#documentation)
* [x ] I have searched for a similar issue in the [project](https://github.com/yourkarma/JWT/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 10.3
 CocoaLumberjack Version | none
 Integration Method      | Cocoapods
 Xcode Version           | 8.3.3
 Repro rate              | always

### Issue Description and Steps

When I use `JWTCryptoKeyExtractor` in my project, I'm getting the following error:
```
Use of unresolved identifier 'JWTCryptoKeyExtractor'
```

There are also a lot of related warnings that come up:
```
/<module-includes>:1:1: Umbrella header for module 'JWT' does not include header 'JWTAlgorithmESBase.h'
/<module-includes>:1:1: Umbrella header for module 'JWT' does not include header 'JWTAlgorithmNone.h'
/<module-includes>:1:1: Umbrella header for module 'JWT' does not include header 'JWTCryptoKey.h'
/<module-includes>:1:1: Umbrella header for module 'JWT' does not include header 'JWTCryptoKeyExtractor.h'
/<module-includes>:1:1: Umbrella header for module 'JWT' does not include header 'JWTCryptoSecurity.h'
```

I'm attaching a demo project that illustrates this.  The only thing I'm doing in the project is integrating via a pod, and I've added one line of code to the ViewController:

`let extractor = JWTCryptoKeyExtractor.publicKeyWithPEMBase64().type`

Any idea of a workaround for this?

[JWTExtractorTest.zip](https://github.com/yourkarma/JWT/files/1163268/JWTExtractorTest.zip)

**Comment by andriajensen** [comment]
@lolgear it looks like this is already fixed in master.  Can you publish a new pod version to include this fix?

**Comment by andriajensen** [comment]
#133 fixed this issue.

**Comment by lolgear** [comment]
Sure! I could post a new beta version asap.

**Comment by lolgear** [comment]
#137

**Comment by lolgear** [comment]
@andriajensen it would be nice if you could add demo/tes-case for your specific issue, thanks!

**Comment by lolgear** [comment]
@andriajensen sorry, I missed! :) I mean previous issue with custom string to data transform. #132

**Comment by lolgear** [comment]
@andriajensen 
could it be closed?
