### ISSUE TITLE
Manual installed JWT lib breaks application during RSA signed jwt verification

### ISSUE THREAD

**Issue by ruslan-bikkinin** [yourkarma/JWT#143]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/yourkarma/JWT/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](https://github.com/yourkarma/JWT#documentation)
* [x] I have searched for a similar issue in the [project](https://github.com/yourkarma/JWT/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios
 Platform Version        |  10
 CocoaLumberjack Version | none
 Integration Method      | manually
 Xcode Version           | Xcode 8
 Repro rate              | all the time (100%)

### Issue Description and Steps

I am using 3.0.0-beta4 library version. My application demands to install JWT manually, so what i did:

* I copied `Core` directory of library into `Libraries/JWT` directory of my project
* Then I remove any 'JWT/' prefixes from any of `import` statements in `Core` files, because compilator could not find any `JWT/JWT.h` files for some reason.
* Then I add code sample from #141 and run application.

My application breaks every time with `EXC_BAD_ACCESS`, when JWT library calls `SecTrustCreateWithCertificates()` method. 

When i install JWT via cocoa pod such problem absents. I looked at #129, #127, #135, but i found nothing helpful for me with that. Obviously, i did something wrong with manual installation of library. Please, could somebody help me to make it properly?

**Comment by lolgear** [comment]
Hi!
Could you make a diff between files that are shipped in each kind of installation?

Also, verify all required frameworks ( Security is a corner stone for all functions in this library ( and all iOS system calls, hic ) ). They should be linked with your output binary.

**Comment by ruslan-bikkinin** [comment]
> Could you make a diff between files that are shipped in each kind of installation?

I am sorry, do you mean to show changes i did to library sources during manual installation?

**Comment by ruslan-bikkinin** [comment]
> Also, verify all required frameworks ( Security is a corner stone for all functions in this library ( and all iOS system calls, hic ) ). They should be linked with your output binary.

I linked my library with `Security.Framework` and `Foundation.Framework` (there are nothing more, i suppose), but it didn't help me.

**Comment by ruslan-bikkinin** [comment]
I fixed problem by adding Base64 library to my project.  @lolgear the only thing that bothering me a little is that i had to remove header path prefixes (`JWT/` and `Base64/`) to prevent `Header can not be found` compilation errors  in those files which errors pointed to. Do you have any thoughts how to manual install libraries without changing their code that way?

**Comment by lolgear** [comment]
@ruslan-bikkinin could you post example project with fix? ( the history of changes would be brilliant )

**Comment by ruslan-bikkinin** [comment]
@lolgear Okay, I'll do it when I will have some time.

**Comment by ruslan-bikkinin** [comment]
@lolgear, hi again, i prepared [demo repository](https://github.com/ruslan-bikkinin/demo_jwt_manual_inst) for you with sample project. This is simple react native project which i have been created using `react-native init` command. All steps of manual installation of JWT library into it are present in it's commits. Before opening project in Xcode, please run `npm i ` from root of it (it requires nodejs to be installed).

Project has `MyCustomLib` library which i created in order to sync project structure of my real project with demo one. There are simple `Main.h` and `Main.m` files, which contains one simple method `runJwtDecoding`. I will use later it to run sample code from `demo_jwt_manual_inst\AppDelegate.m:21`. What I did then: I copied `Core` directory and `LICENSE` file of JWT library into `demo_jwt_manual_inst\Libraries\MyCustomLib\JWT`. Then I added this directory as groups to the `Libraries` group of project. Beginning from this moment, I started to get build errors as I described earlier. Then I added sample code to `runJwtDecoding`function. Then i added Base64 library to the project the same way.  That's it, to fix build Errors all `JWT\` and `Base64\` prefixes should be deleted from `#import ...` statements. I will be very appreciated if you help me to achieve libraries integration without touching it's code.

**Comment by lolgear** [comment]
@ruslan-bikkinin your approach assume that source code uses 'as-is' without additional libraries or frameworks.

Statement
```objective-c
#import <JWT/JWT.h>
```
Means that you would like to search for target named JWT with JWT.h umbrella header.

Statement
```objective-c
#import "JWT.h"
```
Means that you would like to search in user space ( in project space, as you wish ) or in main target space.

So, it is correct that in your case import statement could not find any headers in JWT target.

For simplicity and against error-rising approach, you could add JWT repository as submodule.

1. Add repository as submodule to your project.
2. Add JWT.xcodeproj to your project ( or create xcworkspace for that reason )
3. Add dependency for your library ( JWT.xcodeproj has static library for this case )
4. Have fun!

**Comment by ruslan-bikkinin** [comment]
@lolgear thank you for your response! I followed steps you provided, but unfortunately have no idea how to deal with Base64, because it's need to be added as submodule too. Well, i updated my repo, please take a look what I did and if i did something wrong point it to me.

**Comment by lolgear** [comment]
@ruslan-bikkinin hi,
JWT library doesn't rely on Base64 library. They are weak coupled. So, if you have Base64 library, you could use it with JWT.

**Comment by ruslan-bikkinin** [comment]
@lolgear yes, i understand that and I tried to integrate Base64 library independently from JWT, but for some reason JWT can not find it. Please, take a look at demo repo, may be you could help me to configure  it correctly. That's the only trouble here for now.

**Comment by lolgear** [comment]
@ruslan-bikkinin 
The simplest way to install JWT in your case - just don't install Base64 framework. :)

I am not sure if it is necessary for you, because it is a legacy dependency for CocoaPods dependencies manager.

**Comment by ruslan-bikkinin** [comment]
@lolgear unfortunately, if Base64 framework will be abscent, JWT verification will lead to BAD_EXCL and app crash. I don't know why.

**Comment by lolgear** [comment]
@ruslan-bikkinin 
#144 try latest master

**Comment by ruslan-bikkinin** [comment]
@lolgear thanks for the support, I have followed steps and advices you provided and now demo is working well without crashes. If instructions of how to manually install library in the project was in the docs it would save a lot of time for me 😃 
Please, if you will have free time add missing documentation section about manual library installation. Thanks again for helping me.
