### ISSUE TITLE
Update release version

### ISSUE THREAD

**Issue by lolgear** [yourkarma/JWT#16]
Update release version to access new features in master via cocoapods installation

**Comment by klaaspieter** [comment]
I tried to do a quick release, but `pod spec lint` rejects the build. 

I don't have time to look into this right now unfortunately. I'll try again later this week. Or if you want you can take a look at the problem by checking out the 1.1.0 branch and running `pod spec lint`.

This is the error I'm getting:

```
The following build commands failed:
	CompileC /var/folders/yx/fmtkd7v13fg1k8jvjwycggz80000gn/T/CocoaPods/Lint/build/Pods.build/Release/JWT.build/Objects-normal/x86_64/JWT.o JWT/JWT/JWT.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
 -> JWT (1.1.0)
    - ERROR | xcodebuild: Returned an unsuccessful exit code.
    - ERROR | xcodebuild:  JWT/JWT/JWT.m:16:9: error: 'MF_Base64Additions.h' file not found with <angled> include; use "quotes" instead

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 2 errors.
```

**Comment by lolgear** [comment]
I think that the problem is plain import statements. Cocoapods prefer umbrellas `<Lib/Header.h>`

**Comment by lolgear** [comment]
Check this one: #17

**Comment by klaaspieter** [comment]
Done.
