### ISSUE TITLE
Compilation error: No known class method for selector 'withBase64String'

### ISSUE THREAD

**Issue by aksonov** [yourkarma/JWT#189]
JWTAlgorithmDataHolder.m:251
latest master

Btw, Cocoapods 2.2.0 version has a lot of compilation errors too, how to use this package?

**Comment by lolgear** [comment]
try latest available version:
3.0.0-beta.8

Which target version do you have? ( macOS 10.9 / iOS 8 etc )?

**Comment by aksonov** [comment]
I tried 3.0.0-beta.8 
Target is iOS 11

**Comment by lolgear** [comment]
@aksonov 
I recently upload 3.0.0-beta.8 to CocoaPods.

**Comment by aksonov** [comment]
Just tried again, the result is exactly the same…  Where is withBase64String method?

**Comment by lolgear** [comment]
@aksonov 
JWTBase64Coder.h

Could you post your Podfile?

**Comment by aksonov** [comment]
```
platform :ios, '9.0'

def testing_pods
    pod 'XMPPFramework', :git => "https://github.com/aksonov/XMPPFramework.git", :branch => '3.7.3'
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'React', path: '../node_modules/react-native', :subspecs => [
        'Core',
        'RCTActionSheet',
        'RCTAnimation',
        'RCTGeolocation',
        'RCTImage',
        'RCTLinkingIOS',
        'RCTNetwork',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket',
        'BatchedBridge'
    ]
    pod 'GoogleMaps'
    pod 'RNXMPP', :path => '../node_modules/react-native-xmpp'
    pod 'react-native-mixpanel', path: '../node_modules/react-native-mixpanel'
    pod 'react-native-maps', :path => '../node_modules/react-native-maps'
    pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
    pod 'CodePush', :path => '../node_modules/react-native-code-push'
    pod 'react-native-blur', :path => '../node_modules/react-native-blur'
    pod 'RNBackgroundGeolocation', :path => '../node_modules/react-native-background-geolocation'
    pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'
    pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
    pod 'RSKImageCropper'
    pod 'QBImagePickerController'
    pod 'Firebase/Core'
    pod 'JWT', '~> 3.0.0-beta.8'
    pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
    pod 'Firebase/Auth'
    pod 'BugsnagReactNative', path: '../node_modules/bugsnag-react-native/'
end

target 'tinyrobot' do
    testing_pods
end

target 'tinyrobotStaging' do
    testing_pods
end

target 'tinyrobotTesting' do
    testing_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end

    if target.name == "React"
      target.remove_from_project
    end
  end
end
```

**Comment by lolgear** [comment]
@aksonov 
Try to delete Podfile.lock and run `pod update` to fetch latest updates.

**Comment by aksonov** [comment]
Ooops, looks like I found the reason - CodePush pod uses JWT too and probably it is lower version, so it doesn't see new signature... It looks like I have to fork react-native-codepush module to solve this, right?

**Comment by lolgear** [comment]
@aksonov 
I suppose that you can remove JWT from Podfile (it would be installed by CodePush) or install it via subspec of react-native-codepush.

I do not understand why they do it like this. 
They could add a dependency in pod spec but they decided to copy ( or add git sub-module ).
Because since December ( latest update in their repository ) some necessary bugs are fixed.

However, you could log your example ( console output + podfile / podfile.lock ) and ask CocoaPods guys about this.
If there is no warning about versions collision, you could submit issue/PR in CocoaPods.

**Comment by aksonov** [comment]
Thank you for the fast reply. I guess Microsoft team did it to allow non-cocoapods installation, so I will wait until they updated your great package.
