### ISSUE TITLE
How to encode with 2.0? All encode methods marked as deprecated.

### ISSUE THREAD

**Issue by falkobuttler** [yourkarma/JWT#47]
How am I supposed to encode a payload now? All encode methods in JWT.h are marked as deprecated. Even the documentation is using the deprecated version...

**Comment by lolgear** [comment]
See documentation section "Fluent Style".

`[JWT encodePayload:]` or `[JWT decodeMessage:]` as a start point to fluent.

`NSString *jwt = [JWT encodePayload:payload].secret(secret).encode;`

**Comment by falkobuttler** [comment]
Thanks, it would be great if the documentation would also clearly reflect that. The first section is still referring to ``[JWT encodePayload:@{@"foo": @"bar"} withSecret:@"secret"];`` as of now.

**Comment by lolgear** [comment]
@falkobuttler yep, as soon as possible documentation will be updated and separated into versions sections

**Comment by lolgear** [comment]
#48

**Comment by lolgear** [comment]
@falkobuttler closed?

**Comment by falkobuttler** [comment]
Yes 👍
