### ISSUE TITLE
Problem with encodePayload

### ISSUE THREAD

**Issue by rich-armstrong** [yourkarma/JWT#5]
Hey guys, I enjoy the library, but I think I may be using it slightly wrong and have a question and example.

I believe the return I'm getting from encodePayload may not be as desired, I'm expected header.payload.signature, is that what this method should be returning? That does appear what it looks like when I read through the code and move through the debugger. =/ However, I seem to only get returned the signed payload. Any help would be greatly appreciated =D

Thank you,
Richard

When using the encodePayload method:
=========================================

    #import <JWT.h>

    NSDictionary * payload = @{@"jti":     @"ahFzfnJlYWxtYXNzaXZlLW1tc3ImCxIEVXNlchiAgIDampnSCAwLEghBcGlUb2tlbhiAgICAgOSRCgw",     @"url": @"/api/v1/markets"};
     NSString * secret = @"f248e3cb-f22c-49e6-b1ae-125f079f0afc";

     NSString * token = [JWT encodePayload:payload withSecret:secret];
    NSLog(@"result: %@", token);

`result:     4jELBD4GCMGRUjAheW9g905Dj1TtuuwN/bSiLoq+1BD3nt9vh93gDqoYhNbIy4BjjfNvFo4jqN21lRWUIhQCnQ==`

=========================================

My issue:
I receive only the encoded payload

Expected Result:
header.payload.signature

the header and payload I can easily get to 64bit encoded, however I haven't been able to encode "header.payload" with the secrete

has this been seen before, or does anyone know what I might be doing wrong?

**Comment by klaaspieter** [comment]
I'm not 100% sure what you're trying to achieve. Are you trying to use custom header values? The [header](https://github.com/yourkarma/JWT/blob/master/JWT/JWT.m#L36) is hardcoded at the moment, but that shouldn't be hard to change. Feel free to offer a PR.
