### ISSUE TITLE
Can't Generating Token Giving Error For base64UrlEncodedString.

### ISSUE THREAD

**Issue by Premal-Khetani** [yourkarma/JWT#58]
I am using the library to generate the token for the data. Every time i run the app and it crash and give me following error 

>  -[NSConcreteData base64UrlEncodedString]: unrecognized selector sent to instance 0x7fa9ba8145b0

> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSConcreteData base64UrlEncodedString]: unrecognized selector sent to instance 0x7fa9ba8145b0'

I put debug points and found that in the JWT.m file there is method named** - (NSString *)encodeSegment:(id)theSegment withError:(NSError **)error **. In this method there is the code as below 

`NSString *encodedSegment = nil;
    
    if (encodedSegmentData) {
        encodedSegment = [encodedSegmentData base64UrlEncodedString];
    }`

Here at this point encodedSegment  throws error as given above. Please help me to resolve this. 

Thank you.

Premal Khetani

**Comment by lolgear** [comment]
@Premal-Khetani please, add library version. And also your invocation of jwt.

**Comment by Premal-Khetani** [comment]
@lolgear Library Version  is 2.0 And i am doing it as below :

 `NSDictionary *jsonDataTobeEncode = @{@"sub":@"Testing",@"name":@"Premal",@"admin": @true};
    NSString *jwtTokenValue = [JWTBuilder encodePayload:jsonDataTobeEncode].secret(@"MySecrateKey").algorithm([JWTAlgorithmFactory algorithmByName:@"HS256"]).encode;`

Please take a look.

**Comment by lolgear** [comment]
@Premal-Khetani how did you add library to your project?

**Comment by Premal-Khetani** [comment]
I added it by Pod install @lolgear

**Comment by lolgear** [comment]
@Premal-Khetani  could you post entries of JWT from `Podfile` and from `Podfile.lock` ?

**Comment by lolgear** [comment]
@Premal-Khetani actual or could be closed?

**Comment by Premal-Khetani** [comment]
Hello sorry for the late reply I remove all pods and update it by new pod it solved the problem after so may tries. Thank you
