### ISSUE TITLE
what if I don't have a secret? Is that always necessary?

### ISSUE THREAD

**Issue by haemi** [yourkarma/JWT#6]
e.g. in the layer documentation I don't find any information for secret:

https://developer.layer.com/docs/ios/guides

**Comment by klaaspieter** [comment]
I'm not familiar with the specifics of the Layer SDK. At first glance it seems that the Key ID is their equivalent of the secret. 

> Key ID - In order to acquire a Key ID, you must first generate an RSA cryptographic key pair by clicking the button below. Layer will upload the public portion to our service and the private key will appear in a pop up. Please copy and save the private key as it must be retained by your backend application and used to sign Identity Tokens.

A quick glance through [the standard](https://self-issued.info/docs/draft-ietf-oauth-json-web-token.html#rfc.section.6) tells me not having a secret is allowed. If you're willing to submit a PR I'd be happy to merge it in.

**Comment by klaaspieter** [comment]
Closed because of inactivity. If you still want this fixed please open a new issue/PR.
