### ISSUE TITLE
RS256 is not working?

### ISSUE THREAD

**Issue by sahil912** [yourkarma/JWT#60]
I am trying to encode payload using RS256, and encoded result is always nil. Please direct me, If I am missing something here.

**Comment by lolgear** [comment]
@sahil912 any code example? also, if you use fluent style, you can investigate errors by `.jwtError` property after encode/decode usage.

**Comment by sahil912** [comment]
Sorry, I tried to put private key into secret, didn't know I had to use .p12 file along with passphrase. after trying that it worked.

Thanks. Closing this

**Comment by lolgear** [comment]
@sahil912 it would be great if you add instructions to README file for correct RS256 setup and usage!

**Comment by sahil912** [comment]
Sure, I will do it. :)) Thanks.

On Sat, Apr 2, 2016 at 1:05 PM, Dmitry <notifications@github.com> wrote:

> @sahil912 <https://github.com/sahil912> it would be great if you add
> instructions to README file for correct RS256 setup and usage!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/yourkarma/JWT/issues/60#issuecomment-204667677>
>



-- 
Regards
Sahil J
