### ISSUE TITLE
Whitelist allowed algorithm types and decode without specifying just one?

### ISSUE THREAD

**Issue by benguild** [yourkarma/JWT#70]
I don't understand the point of calling both `.algorithmName()` and `.whitelist()` in order to decode. The current code fails without specifying an algorithm yet for some reason also accepts a whitelist?

Shouldn't it accept any whitelisted algorithm, and just check the header for which one to use? **Current code with seemingly conflicting logic/failures:**

``` objc
        //It is insecure to trust the header's value for the algorithm, since
        //the signature hasn't been verified yet, so an algorithm must be provided
        if (!theAlgorithmName) {
            *theError = [JWT errorWithCode:JWTUnspecifiedAlgorithmError];
            return nil;
        }

        NSString *headerAlgorithmName = header[@"alg"];

        //If the algorithm in the header doesn't match what's expected, verification fails
        if (![theAlgorithmName isEqualToString:headerAlgorithmName]) {
            *theError = [JWT errorWithCode:JWTUnsupportedAlgorithmError];
            return nil;
        }

        //If a whitelist is passed in, ensure the chosen algorithm is allowed
        if (theWhitelist) {
            if (![theWhitelist containsObject:theAlgorithmName]) {
                *theError = [JWT errorWithCode:JWTUnsupportedAlgorithmError];
                return nil;
            }
        }
```

Related: #50

**Comment by lolgear** [comment]
Uh, yes, clumsy place.
Besides it needs unique error cases.
Any PR suggestion?

**Comment by benguild** [comment]
This was closed without comment. Can I have an update, just out of curiosity?

**Comment by lolgear** [comment]
Version 3.0 will handle "whitelists" in different way. ( 3.0.0-beta.2 have this functionality )
You could choose algorithm and data by setup DataHolder ( Algorithm and data holder, oh, too long name ).
Then you could add data holders in chain to try to decode/encode. ( try first, fail, try next ... )
