### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by WingedToaster** [yourkarma/JWT#71]
I am noticing a memory leak in Instruments when encoding a claim set using any Algorithm except for JWTAlgorithmNone. 

The issue appears to be `unsigned char* cHMAC = malloc(fullSize);` not getting freed when encoding the payload in the `JWTAlgorithmHSBase` class. Pull Request forthcoming...

**Comment by lolgear** [comment]
Thanks!

**Comment by lolgear** [comment]
@WingedToaster fixed? Please, close issue when you will be sure.

**Comment by WingedToaster** [comment]
It's fixed and deployed live with no issues. Closing.
