### ISSUE TITLE
[Badly broken] Lack of consistent Base64 URL encoding causes Base64 decoding failure

### ISSUE THREAD

**Issue by benguild** [yourkarma/JWT#74]
Hi, this library is broken and I cannot recommend its current use in modern applications. I posted another issue about whitelisting inconsistencies #70, but also I want to point out that by not using the `dataWithBase64UrlEncodedString` method added to `NSData` to decode inbound JSON instead of the current `dataWithBase64String` completely hoses its decoding abilities and simply returns `nil` if the padding is omitted... **as is specified in the JWT spec**. #8 #10

**Comment by lolgear** [comment]
@benguild 
thanks!
I've found these heinous lines in decoding part.
```
    // decode headerPart
    NSError *jsonError = nil;
    NSData *headerData = [NSData dataWithBase64String:headerPart];
```

```
    // and decode payload
    jsonError = nil;
    NSData *payloadData = [NSData dataWithBase64String:payloadPart];
```

**Comment by benguild** [comment]
... Where it occurs? I don't understand. I stopped using the library already because of its incompatibility.

**Comment by lolgear** [comment]
@benguild 'where this behavior occurs'
all tests passed. Not all cases covered. Repair needed.
Library use base64url encoding in encoding jwt.
So, if you use it for decoding ( without any trimming ), nothing bad happens.
