### ISSUE TITLE
Error with pods: Embedded dylibs/frameworks are only supported on iOS 8.0 and later

### ISSUE THREAD

**Issue by roma86** [yourkarma/JWT#78]
Hello. Thank you for work.

I tried to install this library as conterpart of https://github.com/kylef/JSONWebToken.swift in reason to support iOS 7 min build target.

After `pod install` i have an error

```
ld: embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/Base64.framework/Base64) for architecture armv7
```
But, **JWT.podspec*** declare 

```
s.ios.deployment_target = '6.0'
```

**Comment by lolgear** [comment]
thanks for feedback!
It seems that inconsistency ( with podspec ) still exists.
I think that JWT should support the minimum of iOS version ( 6 or 7 ).

**Comment by lolgear** [comment]
@roma86 
could you share project that mimic current behavior?

**Comment by roma86** [comment]
@lolgear i send you invite to access the project files on Google Drive.

Notes:
- Project cleaned from private business logic, only third party sources and pods dependencies remained. 
- Open xworkspace and try to build to get build error
- [Optionally] remove Pods dir and Podfile.lock and run `pod install` – you can see error still here
- cocoapods version 1.0.0 and 1.0.1 deliver same result

Thank you

**Comment by lolgear** [comment]
@roma86 I think that the answer is:

http://stackoverflow.com/questions/29728487/does-cocoapod-use-frameworks-work-with-ios7

**Comment by roma86** [comment]
@lolgear thank you
