### ISSUE TITLE
Base64 encoding uses padding

### ISSUE THREAD

**Issue by keyboardsamurai** [yourkarma/JWT#8]
RFC7515 -> https://www.rfc-editor.org/rfc/rfc7515.txt specifically demands that no padding be added to base64 encoded data and recommends the replacement of all padding characters as described in Appendix C.

Currently the JWT library uses the Base64 pod to provide padded base64 data though, breaking some server implementations that strictly adhere to the RFC standard.

For the header and payload part the fix is pretty straightforward.

	+ (NSString *)encodeSegment:(id)theSegment;
	{
	    NSError *error;
	    NSString *encodedSegment = [[NSJSONSerialization dataWithJSONObject:theSegment options:0 error:&error] base64String];

	    NSAssert(!error, @"Could not encode segment: %@", [error localizedDescription]);

	    encodedSegment = [encodedSegment stringByReplacingOccurrencesOfString:@"=" withString:@""];
	    encodedSegment = [encodedSegment stringByReplacingOccurrencesOfString:@"+" withString:@"-"];
	    encodedSegment = [encodedSegment stringByReplacingOccurrencesOfString:@"/" withString:@"_"];
	    
	    return encodedSegment;
	}

For the signature part though, I wasn't able to figure out how encodePayload works yet.

**Comment by klaaspieter** [comment]
Closed by #10
