### ISSUE TITLE
Custom headers feature

### ISSUE THREAD

**Issue by lolgear** [yourkarma/JWT#9]
It would be great if we could configure our headers and add them to standard headers or replace standard headers

**Comment by klaaspieter** [comment]
It's not something we're planning to add, but it shouldn't be difficult to add yourself. If you're up for making a PR, I can merge it in.

**Comment by lolgear** [comment]
@klaaspieter, pull request is ready, could you review it?

**Comment by klaaspieter** [comment]
Closed by #11
